export const MODAL_STYLES_ADD_CREDIT_CARD = {
  true: {
    cardMaxWidth: 'max-w-[195px]',
    cardHeaderGap: 'gap-0',
    headerContentGap: 'gap-1',
    payPassIcon: 'w-[11px] h-[14px]',
    cardBody: 'mb-[10px] mt-[8px]',
    chipSize: 'w-[24px] h-[16px]',
    worldTextSize: 'text-5xs',
    cardNumberText: 'ml-2 mt-0 text-xs',
    detailsGap: 'mt-0 gap-2',
    expireText: 'text-3xs',
    holderNameText: 'max-w-[115px] text-3xs',
    mastercardIconSize: 'w-[35px]',
  },
  false: {
    cardMaxWidth: 'max-w-[290px]',
    cardHeaderGap: 'gap-2',
    headerContentGap: 'gap-3',
    payPassIcon: 'unset',
    cardBody: 'mb-[18px] mt-[14px]',
    chipSize: 'unset',
    worldTextSize: 'text-2xs',
    cardNumberText: 'ml-4 mt-1 text-sm',
    detailsGap: 'mt-2 gap-5',
    expireText: 'text-2xs',
    holderNameText: 'max-w-[185px] text-xs',
    mastercardIconSize: 'unset',
  },
};
